# Generated by Django 4.2.5 on 2023-09-14 07:52

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='finishing_date',
            field=models.DateField(blank=True, null=True, verbose_name='finishing date'),
        ),
        migrations.AddField(
            model_name='post',
            name='starting_date',
            field=models.DateField(blank=True, null=True, verbose_name='starting date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
