# Generated by Django 4.2.5 on 2023-09-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='finishing_date',
            field=models.DateField(blank=True, null=True, verbose_name='finishing date'),
        ),
        migrations.AddField(
            model_name='post',
            name='starting_date',
            field=models.DateField(blank=True, null=True, verbose_name='starting date'),
        ),
    ]
